# Generated by Django 6.0.3 on 2026-03-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hulegeb', max_length=200)),
                ('heading_part1', models.CharField(default='Weaving', max_length=200)),
                ('heading_part2', models.CharField(default='Dignity', max_length=200)),
                ('heading_part3', models.CharField(default=', Crafting Independence', max_length=200)),
                ('description', models.TextField(default="For over 70 years, Hulegeb has been led by and for Ethiopia's blind and physically disabled community — turning skill into steady, dignified livelihoods.")),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_slides/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL (if not uploading file)', max_length=500)),
                ('image_alt', models.CharField(default='Hulegeb artisans at work', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
