# Generated by Django 6.0.3 on 2026-03-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title', max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=300, unique=True)),
                ('excerpt', models.TextField(help_text='Short description/summary', max_length=500)),
                ('content', models.TextField(help_text='Full blog post content')),
                ('featured_image', models.ImageField(blank=True, help_text='Upload featured image', null=True, upload_to='blog/')),
                ('featured_image_url', models.URLField(blank=True, help_text='Or provide external image URL', max_length=500)),
                ('image_alt', models.CharField(default='Blog post image', max_length=200)),
                ('author', models.CharField(default='Hulegeb Team', max_length=100)),
                ('published_date', models.DateField(help_text='Publication date')),
                ('is_published', models.BooleanField(default=True, help_text='Show on website')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Media title or caption', max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Type of media', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='gallery/images/')),
                ('image_url', models.URLField(blank=True, help_text='Or provide an external image URL', max_length=500)),
                ('video', models.FileField(blank=True, help_text='Upload a video file (MP4, WebM)', null=True, upload_to='gallery/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Or provide an external video URL (YouTube, Vimeo, etc.)', max_length=500)),
                ('video_thumbnail', models.ImageField(blank=True, help_text='Thumbnail for video', null=True, upload_to='gallery/thumbnails/')),
                ('alt_text', models.CharField(default='Gallery media', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='hero_slides/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide an external image URL', max_length=500),
        ),
    ]
